apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    type: nfs-kubernetes
spec:
  storageClassName: aws-efs
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: fs-9ba8aeda.efs.ap-southeast-1.amazonaws.com
    readOnly: false