apiVersion: v1
kind : Secret
metadata :
  name: secret-fb
type: Opaque
data:
  DB_USER: # $echo 'user' | base64
  DB_PASS: # $echo 'pass' | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-configmap
data:
  config.php: |
        <?php
        $db_host = "endpoint RDS/your host";
        $db_user = getenv("DB_USER");
        $db_pass = getenv("DB_PASS");
        $db_name = "dbdummy";
        try {
        //create PDO connection
        $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
        } catch(PDOException $e) {
        //show error
        die("Terjadi masalah: " . $e->getMessage());
        }
