kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
#        env:
#        - name: WORDPRESS_DB_HOST
#          value: dbmaster.ckw1ddumtncz.ap-southeast-1.rds.amazonaws.com
#        - name: WORDPRESS_DB_PASSWORD
#          value: ***
#        - name: WORDPRESS_DB_USER
#          value: root
        ports:
        - containerPort: 80 
      restartPolicy: Always
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: wordpress-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#  - host: blog.gonnabegood.xyz
#    http:
#      paths:
      #- path: /
#      - backend:
#          serviceName: wordpress-service
#          servicePort: 80